services:
  postgres:
    image: postgres:16
    container_name: csc-db
    environment:
      POSTGRES_DB: CSC-DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ayrton175
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
