spring.application.name=System-Finances

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/CSC-DB
spring.datasource.username=postgres
spring.datasource.password=ayrton175
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
